version: "3"

services:
        caddy:
                image: caddy:2-alpine
                restart: unless-stopped
                ports:
                        - "80:80"
                        - "443:443"
                volumes:
                        - ./caddy/Caddyfile:/etc/caddy/Caddyfile
                        - ./caddy/data:/data
                        - ./caddy/config:/config

        db:
                image: mysql:8
                restart: unless-stopped
                env_file: .env
                command: --default-authentication-plugin=mysql_native_password
                volumes:
                        - ./mysql/data:/var/lib/mysql

        ghost:
                image: ghost:4-alpine
                restart: unless-stopped
                depends_on:
                        - caddy
                        - db
                env_file: .env
                volumes:
                        - ./config.production.json:/var/lib/ghost/config.production.json
                        - ./content:/var/lib/ghost/content
