version: "3"

services:
        caddy:
                image: caddy:2-alpine
                restart: unless-stopped
                ports:
                        - "80:80"
                        - "443:443"
                volumes:
                        - ./caddy/Caddyfile:/etc/caddy/Caddyfile
                        - ./caddy/data:/data
                        - ./caddy/config:/config

        ghost:
                image: ghost:4-alpine
                restart: unless-stopped
                depends_on:
                        - caddy
                env_file: .env
                volumes:
                        - ./config.production.json:/var/lib/ghost/config.production.json
                        - ./content:/var/lib/ghost/content
